CFLAGS=-std=gnu99 -O3 -Wall -Wextra -Werror -Wstrict-prototypes -Wno-parentheses -Wno-unused-function -Wno-unused-variable

run: demo
	./demo

demo: demo.c libpg2.a
	$(CC) $(CFLAGS) -I. -L. -g -odemo demo.c -lpg2 -lSDL2 -lm

libpg2.a: pg.c pgOpenType.c platform.linux.c pg.h
	$(CC) $(CFLAGS) -c pg.c pgOpenType.c platform.linux.c
	ar rcs libpg2.a *.o

clean:
	rm *.o *.a

install:    libpg2.a
	cp pg.h /usr/include
	cp libpg2.a /usr/lib

uninstall:
	rm /usr/include/pg.h
	rm /usr/lib/libpg2.a

